# Jekyll configuration for SpecJet CLI documentation
title: SpecJet CLI Documentation
description: API contract collaboration tool - Generate TypeScript types and mock servers from OpenAPI contracts
baseurl: ""
url: "https://docs.specjet.dev"

# Theme configuration
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

# Just the Docs theme configuration
heading_anchors: true
permalink: pretty
markdown: kramdown
highlighter: rouge

# Navigation
nav_external_links:
  - title: "GitHub"
    url: "https://github.com/specjet-api/specjet"
  - title: "Main Site"
    url: "https://specjet.dev"

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s\-/]+/
  rel_url: true
  button: false

# Table of contents
mermaid:
  version: "9.1.3"

# Google Analytics
google_analytics: G-0G7YF4G3RT

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "https://github.com/specjet-api/specjet"
  "SpecJet.dev":
    - "https://specjet.dev"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Footer configuration
footer_content: "Copyright &copy; 2025 SpecJet. Open source CLI for API contract development."

# Custom CSS/JS
ga_tracking: G-0G7YF4G3RT

# Exclude files from processing
exclude:
  - node_modules/
  - "*.gemspec"
  - "*.gem"
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - script/
  - LICENSE.txt
  - lib/
  - bin/
  - README.md
  - Rakefile

# Collections - not needed for this setup but good to have
collections_dir: docs

# Kramdown settings
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Plugin configuration
plugins:
  - jekyll-default-layout
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-titles-from-headings